server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
logging:
  level:
    lombok.extern.log4j: debug